const CATEGORY_CONFIG = {
  'reels-shorts': { ratio: '9/16', thumbSize: 'w600-h900' },
  'corporate': { ratio: '16/9', thumbSize: 'w800-h450' },
  'cinematic': { ratio: '21/9', thumbSize: 'w900-h386' },
  'motion-graphics': { ratio: '1/1', thumbSize: 'w800-h450' },
  'logo-reveal': { ratio: '16/9', thumbSize: 'w600-h600' },
  'kineatic-stomp': { ratio: '1/1', thumbSize: 'w800-h450' },
  'ppt-designs': { ratio: '4/3', thumbSize: 'w800-h600' },
  'static-posters': { ratio: '2/3', thumbSize: 'w600-h900' },
  'rotract': { ratio: '1/1', thumbSize: 'w800-h450' },
};

const PORTFOLIO_ITEMS = [
  {
    name: "Video 1",
    category: "kineatic-stomp",
    categoryLabel: "Kineatic and Stomp Typographic Videos",
    desc: "Kineatic and Stomp Typographic Video",
    driveId: "1eREZXf67T2ivna5ot1SFl2YhmXE_fRoh",
    thumbnail: "thumbnails/video1_thumb.png",
  },
  {
    name: "Video 2",
    category: "kineatic-stomp",
    categoryLabel: "Kineatic and Stomp Typographic Videos",
    desc: "Kineatic and Stomp Typographic Video",
    driveId: "1HRoCQJFQ7-PPlTorZdyIx0EmDqf4UgUw",
    thumbnail: "thumbnails/video3_thumb.png",
    revealDelay: 2,
  },
  {
    name: "Video 1",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1Ubf0Tj0Ry_B93ZkuFjwsFCdvTC678u1R",
    thumbnail: "thumbnails/01 Reels and Shorts.png",
  },
  {
    name: "Video 2",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1-ShnFAvB4pYdJT8CGFhd1C5Zd5Np9ji3",
    thumbnail: "thumbnails/02 Reels and Shorts.png",
  },
  {
    name: "Video 3",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1PlFBySV7K7x1eOK7MIcR6kHrB44XPtQB",
    thumbnail: "thumbnails/03 Reels and Shorts.png",
  },
  {
    name: "Video 4",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "17-vN_isrZGB2wMauRxP6qbiWevKQWORU",
    thumbnail: "thumbnails/04 Reels and Shorts.png",
  },
  {
    name: "Video 5",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1uIr859gsb7YpAoJkKGYb8FhFcBptOpBf",
    thumbnail: "thumbnails/05 Reels and Shorts.png",
  },
  {
    name: "Video 6",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1Zqw7oepq2fMedipyhhgFSj5h5ZssyChF",
    thumbnail: "thumbnails/06 Reels and Shorts.png",
  },
  {
    name: "Video 7",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1Fox6vAWiGtuiMDiUnQOTNcJi80X2aoKe",
    thumbnail: "thumbnails/07 Reels and Shorts.png",
  },
  {
    name: "Video 8",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1iVnq0dQh3Y-4bri0AJF5xunkjl0yLw1b",
    thumbnail: "thumbnails/08 Reels and Shorts.png",
  },
  {
    name: "Video 9",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1L1ekDjdLhrNWdjzT3nkQubghq3Qd0MNO",
    thumbnail: "thumbnails/09 Reels and Shorts.png",
  },
  {
    name: "Video 10",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "18IW3QOwWnlpi3qc3yQ7nO22hU2qsP10O",
    thumbnail: "thumbnails/10 Reels and Shorts.png",
  },
  {
    name: "Video 11",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1Wz_H1go3fazHMU2PJDL9Mtj5oHHgFmRj",
    thumbnail: "thumbnails/11 Reels and Shorts.png",
  },
  {
    name: "Video 12",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1ehtnu3xfvUi8zy6goe0rrCvgDrOd1VkP",
    thumbnail: "thumbnails/12 Reels and Shorts.png",
  },
  {
    name: "Video 13",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "14sOGaO5sm4D4j44g3JfjFKGPzyX8FnA9",
    thumbnail: "thumbnails/13 Reels and Shorts.png",
  },
  {
    name: "Video 14",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1SFgMV-n1yDDtXQeg0ERuIiWQXUcEUkGq",
    thumbnail: "thumbnails/14 Reels and Shorts.png",
  },
  {
    name: "Video 15",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "141vMKuzMc5JuAxLpKwcNm7zl7qO2-4vt",
    thumbnail: "thumbnails/15 Reels and Shorts.png",
  },
  {
    name: "Video 16",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "11HcW0Yp-9J36DflXFjiQRS4EZh92odfJ",
    thumbnail: "thumbnails/16 Reels and Shorts.png",
  },
  {
    name: "Video 17",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1eUnngiyOBH96teN14vFgfUwI5rXEjaS7",
    thumbnail: "thumbnails/17 Reels and Shorts.png",
  },
  {
    name: "Video 1",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1o_tAJkN5z94DkaYcuY1LZt2A2Jkdaho0",
    thumbnail: "thumbnails/01 Corporate.png",
  },
  {
    name: "Video 2",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1lxqO05wtLtkvHY-52th-t4Vr_y0XsGl8",
    thumbnail: "thumbnails/02 Corporate.png",
  },
  {
    name: "Video 3",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1ZaJWb69owAXFtW7rDeMz0oHNpDK7P1CN",
    thumbnail: "thumbnails/03 Corporate.png",
  },
  {
    name: "Video 4",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1ZaJWb69owAXFtW7rDeMz0oHNpDK7P1CN",
    thumbnail: "thumbnails/04 Corporate.png",
  },
  {
    name: "Video 4",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1Nv1oxTqHhxPnzeFJ6WK7ucr7PdZofBKV",
    thumbnail: "thumbnails/04 Corporate.png",
  },
  {
    name: "Video 5",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1145WpiO68Q9uy9HkpQ9Via6IhTUC08JR",
    thumbnail: "thumbnails/05 Corporate.png",
  },
  {
    name: "Video 6",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1vj7P5GDD5c09lecFLIt5Tgw-32WyrO58",
    thumbnail: "thumbnails/06 Corporate.png",
  },
  {
    name: "Video 7",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1uyHVnGxZVj9d1q3sVOrjXXl8hQ88YHdI",
    thumbnail: "thumbnails/07 Corporate.png",
  },
  {
    name: "Video 8",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1o0kYY56RQyqCqi6Q-ER3U5FtH9tvRpX8",
    thumbnail: "thumbnails/08 Corporate.png",
  },
  {
    name: "Video 9",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1pOcJ31Xaw_XsZjSh9spsXC9VLS2lINR5",
    thumbnail: "thumbnails/09 Corporate.png",
  },
  {
    name: "Video 10",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "16-g5yW4ISnCthj6l3vAxhDyiV1svPmcY",
    thumbnail: "thumbnails/10 Corporate.png",
  },
  {
    name: "Video 11",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1QpwF4fVwrKq2qVWo4OnHX1SH_FycWEdz",
    thumbnail: "thumbnails/11 Corporate.png",
  },
  {
    name: "Video 1",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "1DP6ny-uxqXypdEmOrmOp7i709n1Ks94v",
    thumbnail: "thumbnails/01 Cinematic.png",
  },
  {
    name: "Video 2",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "1rSV66T4ou_JmpSLFafjNq-SsozaAx46J",
    thumbnail: "thumbnails/02 Cinematic.png",
  },
  {
    name: "Video 3",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "1sxVPxQ-VANMh1r8JrBrKHQWQj4T6acDY",
    thumbnail: "thumbnails/03 Cinematic.png",
  },
  {
    name: "Video 4",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "16S0cLQvo_Qo0QCr1kZBbvKh6_Ja-vfyK",
    thumbnail: "thumbnails/04 Cinematic.png",
  },
  {
    name: "Video 5",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "1XXHebbOgiTIvirqE-PCVnLkiAbI8kHsC",
    thumbnail: "thumbnails/05 Cinematic.png",
  },
  {
    name: "Video 6",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "17yNIf6QA-j8UwjsVz1WfrS1A9eJwSm_5",
    thumbnail: "thumbnails/06 Cinematic.png",
  },
  {
    name: "Video 7",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "15Ia1mscZsQh5lmCVsJTzbLhcregPESOv",
    thumbnail: "thumbnails/07 Cinematic.png",
  },
  {
    name: "Video 1",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1D5M8WwrBaYk3R_s-MTih5Z0AiMoJ3YGH",
    thumbnail: "thumbnails/01 Motion Graphics.png",
  },
  {
    name: "Video 2",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1NS4hgBQ-xEIdIP7U662yD_P4nkjpyvy6",
    thumbnail: "thumbnails/02 Motion Graphics.png",
  },
  {
    name: "Video 3",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1IemO2Z4ItaTAnb2BASzLa0s57fu0sTFB",
    thumbnail: "thumbnails/03 Motion Graphics.png",
  },
  {
    name: "Video 4",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1B6_19l7Zg-H3vADshnIypInAUD0JZ33J",
    thumbnail: "thumbnails/04 Motion Graphics.png",
  },
  {
    name: "Video 5",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1AI5Bz5Xjts6KRyWWZoRRddtaxXts0PXA",
    thumbnail: "thumbnails/05 Motion Graphics.png",
  },
  {
    name: "Video 6",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1SOUSiR11eTMmmxRgBK1RPjkUuSp2InGa",
    thumbnail: "thumbnails/06 Motion Graphics.png",
  },
  {
    name: "Video 7",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "16EzQWIgwEMHRI55RFm1rreFBIIBgpDb0",
    thumbnail: "thumbnails/07 Motion Graphics.png",
  },
  {
    name: "Video 8",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1HX3NQKUlgDEC_dkx1OLdk_T6XUQCJ2qp",
    thumbnail: "thumbnails/08 Motion Graphics.png",
  },
  {
    name: "Video 9",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1psBk4j9Nw-izh2M_ULyCHQZzTVTndiGb",
    thumbnail: "thumbnails/09 Motion Graphics.png",
  },
  {
    name: "Video 10",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1yednUyAyx3hnTAXk4Lja9v0ZFm20pE8a",
    thumbnail: "thumbnails/10 Motion Graphics.png",
  },
  {
    name: "Video 1",
    category: "logo-reveal",
    categoryLabel: "logo-reveal Videos",
    desc: "logo-reveal Video",
    driveId: "15QFlt-4G8_Adps7i_dChxvqJSOeBRvXg",
    thumbnail: "thumbnails/Logo Reval 01 copy.png",
  },
  {
    name: "Video  2",
    category: "logo-reveal",
    categoryLabel: "Logo Reveal",
    desc: "Logo Reveal",
    ytId: "VabOmgmCWzU",
  },
  {
    name: "Power Point Presentations 1",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1OdvEwJftl-HOPTYVD49fC1qALCE5KRyF",
  },
  {
    name: "Power Point Presentations 2",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1p_eehpyCWbIWhX3_6rAqrGQPLsYjqBs6",
  },
  {
    name: "Power Point Presentations 3",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1XRWsmwLefRRWu39UicXp9gqv1J90kfcG",
  },
  {
    name: "Power Point Presentations 4",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1uaUnF8_6GSKx8GVuoo9fBmoINJ61H0Cf",
  },
  {
    name: "Power Point Presentations 5",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1OGKmJUROZseuQus0MmqqlvLL2C01b10x",
  },
  {
    name: "Power Point Presentations 6",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1GU5-my1ylAtNkTENrlTj-1wP8NUogpCL",
  },
  {
    name: "Brand Guidelines",
    category: "ppt-designs",
    categoryLabel: "Brand Guidelines",
    desc: "Brand Guidelines",
    driveId: "1gZQud3h6lZ3zQYfJYGZJynga8_tDfSck",
  },
  {
    name: "Design 1",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/01.webp",
  },
  {
    name: "Design 2",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/04.webp",
  },
  {
    name: "Design 3",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/05.webp",
  },
  {
    name: "Design 4",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/06.webp",
  },
  {
    name: "Design 5",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/07.webp",
  },
  {
    name: "Design 6",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/08.webp",
  },
  {
    name: "Design 7",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/1 copy 2.webp",
  },
  {
    name: "Design 8",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/4.webp",
  },
  {
    name: "Design 9",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/6.webp",
  },
  {
    name: "Design 10",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Artboard 1 copy 2.webp",
  },
  {
    name: "Design 11",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Artboard 1 copy.webp",
  },
  {
    name: "Design 12",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Artboard 1.webp",
  },
  {
    name: "Design 13",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Artboard 111.webp",
  },
  // {
  //   name: "Design 14",
  //   category: "static-posters",
  //   categoryLabel: "Static Posters",
  //   desc: "Static Poster Design",
  //   thumbnail: "Static Posters/FYORI Brand Book.webp",
  // },
  {
    name: "Design 15",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/IDFW All Logo Centre LED Wall.webp",
  },
  {
    name: "Design 16",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Overall Talent Awardees@2x 1152.webp",
  },
  {
    name: "Design 17",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Post 06.webp",
  },
  {
    name: "Design 18",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Post 1 V2.webp",
  },
  {
    name: "Design 19",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Poster 2.webp",
  },
  {
    name: "Design 20",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/She Talks Podcast Post.webp",
  },
  // {
  //   name: "Design 21",
  //   category: "static-posters",
  //   categoryLabel: "Static Posters",
  //   desc: "Static Poster Design",
  //   thumbnail: "Static Posters/Stande V2.webp",
  // },
  {
    name: "Design 22",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Static Post 01.webp",
  },
  {
    name: "Design 23",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Static Post 02.webp",
  },
  {
    name: "Design 24",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Static Post 03.webp",
  },
  {
    name: "Design 25",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Static Post 04.webp",
  },
  {
    name: "Design 26",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Static Post 05.webp",
  },
  {
    name: "Design 27",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Static Post 06.webp",
  },
  {
    name: "Design 28",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Static Post 07.webp",
  },
  {
    name: "Design 29",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Static Post 08.webp",
  },
  {
    name: "Design 30",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Static Post 09.webp",
  },
  {
    name: "Design 31",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/Static Post 10.webp",
  },
  // {
  //   name: "Design 32",
  //   category: "static-posters",
  //   categoryLabel: "Static Posters",
  //   desc: "Static Poster Design",
  //   thumbnail: "Static Posters/Valigal [6F21EAF].webp",
  // },
  {
    name: "Design 33",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/post 07.webp",
  },
  {
    name: "Design 34",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/post 08.webp",
  },
  {
    name: "Design 35",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/post 09.webp",
  },
  {
    name: "Design 36",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/post 10.webp",
  },
  {
    name: "Design 37",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/post 11.webp",
  },
  {
    name: "Design 38",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/post 12.webp",
  },
  {
    name: "Design 39",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/s01 copy.webp",
  },
  // {
  //   name: "Design 40",
  //   category: "static-posters",
  //   categoryLabel: "Static Posters",
  //   desc: "Static Poster Design",
  //   thumbnail: "Static Posters/s02.webp",
  // },
  // {
  //   name: "Design 41",
  //   category: "static-posters",
  //   categoryLabel: "Static Posters",
  //   desc: "Static Poster Design",
  //   thumbnail: "Static Posters/sample 01_page-0001.webp",
  // },
  // {
  //   name: "Design 42",
  //   category: "static-posters",
  //   categoryLabel: "Static Posters",
  //   desc: "Static Poster Design",
  //   thumbnail: "Static Posters/standee.webp",
  // },
  {
    name: "Design 43",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/💫 Event No. 347Global Syndicate’s Business Meeting Over CoffeeYour Saturday just got a purpose.heic",
  },
  {
    name: "Design 44",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    thumbnail: "Static Posters/💫 Event No. 351Global Syndicate’s Business Meeting Over CoffeeYour Saturday just got a purpose.heic",
  },
  {
    name: "Rotract Designs",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Designs",
    driveId: "18q25agR-hQK0Rt3N2vyM3KxfY1tJzFoP",
    thumbnail: "thumbnails/01 rotract.png",
  },
  {
    name: "Rotract Designs",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Designs",
    driveId: "1E7g5dH-us8sKN5paKoKFLJmEj7CwepyV",
    thumbnail: "thumbnails/02 portrait Cinematic.png",
  },
  {
    name: "Rotract Design 1",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/00.webp",
  },
  {
    name: "Rotract Design 2",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/000.png",
  },
  {
    name: "Rotract Design 3",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/01.webp",
  },
  {
    name: "Rotract Design 4",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/02.webp",
  },
  {
    name: "Rotract Design 5",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/03.webp",
  },
  {
    name: "Rotract Design 6",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/04.webp",
  },
  {
    name: "Rotract Design 7",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/05.webp",
  },
  {
    name: "Rotract Design 8",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/06.webp",
  },
  {
    name: "Rotract Design 9",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/07.webp",
  },
  {
    name: "Rotract Design 10",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/08.webp",
  },
  {
    name: "Rotract Design 11",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/09.webp",
  },
  {
    name: "Rotract Design 12",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/10.webp",
  },
  {
    name: "Rotract Design 13",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/10a.webp",
  },
  {
    name: "Rotract Design 14",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/10b.webp",
  },
  {
    name: "Rotract Design 15",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/10c.webp",
  },
  {
    name: "Rotract Design 16",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/10d.webp",
  },
  {
    name: "Rotract Design 17",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/11.webp",
  },
  {
    name: "Rotract Design 18",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/12.webp",
  },
  {
    name: "Rotract Design 19",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/13.webp",
  },
  {
    name: "Rotract Design 20",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/14.webp",
  },
  {
    name: "Rotract Design 21",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/15.webp",
  },
  {
    name: "Rotract Design 22",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/16.webp",
  },
  {
    name: "Rotract Design 23",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/17.webp",
  },
  {
    name: "Rotract Design 24",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/18.webp",
  },
  {
    name: "Rotract Design 25",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/19.webp",
  },
  {
    name: "Rotract Design 26",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/20.webp",
  },
  {
    name: "Rotract Design 27",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/21.webp",
  },
  {
    name: "Rotract Design 28",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/22.webp",
  },
  {
    name: "Rotract Design 29",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/23.webp",
  },
  {
    name: "Rotract Design 30",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/24.webp",
  },
  {
    name: "Rotract Design 31",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/25.webp",
  },
  {
    name: "Rotract Design 32",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/26.webp",
  },
  {
    name: "Rotract Design 33",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/27.webp",
  },
  {
    name: "Rotract Design 34",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/28.webp",
  },
  {
    name: "Rotract Design 35",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/29.webp",
  },
  {
    name: "Rotract Design 36",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/30.webp",
  },
  {
    name: "Rotract Design 37",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/31.webp",
  },
  {
    name: "Rotract Design 38",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/32.webp",
  },
  {
    name: "Rotract Design 39",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/33.webp",
  },
  {
    name: "Rotract Design 40",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/34.webp",
  },
  {
    name: "Rotract Design 41",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/35.webp",
  },
  {
    name: "Rotract Design 42",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/36.webp",
  },
  {
    name: "Rotract Design 43",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/37.webp",
  },
  {
    name: "Rotract Design 44",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/38.webp",
  },
  {
    name: "Rotract Design 45",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/39.webp",
  },
  {
    name: "Rotract Design 46",
    category: "rotract",
    categoryLabel: "Rotract Designs",
    desc: "Rotract Design",
    thumbnail: "Rotract/40.webp",
  }
];
