const CATEGORY_CONFIG = {
  'reels-shorts': { ratio: '9/16', thumbSize: 'w600-h900' },
  'corporate': { ratio: '16/9', thumbSize: 'w800-h450' },
  'cinematic': { ratio: '1/1', thumbSize: 'w900-h386' },
  'motion-graphics': { ratio: '1/1', thumbSize: 'w800-h450' },
  'logo-reveal': { ratio: '16/9', thumbSize: 'w600-h600' },
  'kineatic-stomp': { ratio: '1/1', thumbSize: 'w800-h450' },
  'ppt-designs': { ratio: '4/3', thumbSize: 'w800-h600' },
  'static-posters': { ratio: '2/3', thumbSize: 'w600-h900' },
  'rotract': { ratio: '16/9', thumbSize: 'w800-h450' },
};

const PORTFOLIO_ITEMS = [
  {
    name: "Video 1",
    category: "kineatic-stomp",
    categoryLabel: "Kineatic and Stomp Typographic Videos",
    desc: "Kineatic and Stomp Typographic Video",
    driveId: "1eREZXf67T2ivna5ot1SFl2YhmXE_fRoh",
    thumbnail: "thumbnails/video1_thumb.png",
  },
  {
    name: "Video 2",
    category: "kineatic-stomp",
    categoryLabel: "Kineatic and Stomp Typographic Videos",
    desc: "Kineatic and Stomp Typographic Video",
    driveId: "1HRoCQJFQ7-PPlTorZdyIx0EmDqf4UgUw",
    thumbnail: "thumbnails/video3_thumb.png",
    revealDelay: 2,
  },
  {
    name: "Video 1",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1Ubf0Tj0Ry_B93ZkuFjwsFCdvTC678u1R",
    thumbnail: "thumbnails/01 Reels and Shorts.png",
  },
  {
    name: "Video 2",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1-ShnFAvB4pYdJT8CGFhd1C5Zd5Np9ji3",
    thumbnail: "thumbnails/02 Reels and Shorts.png",
  },
  {
    name: "Video 3",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1PlFBySV7K7x1eOK7MIcR6kHrB44XPtQB",
    thumbnail: "thumbnails/03 Reels and Shorts.png",
  },
  {
    name: "Video 4",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "17-vN_isrZGB2wMauRxP6qbiWevKQWORU",
    thumbnail: "thumbnails/04 Reels and Shorts.png",
  },
  {
    name: "Video 5",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1uIr859gsb7YpAoJkKGYb8FhFcBptOpBf",
    thumbnail: "thumbnails/05 Reels and Shorts.png",
  },
  {
    name: "Video 6",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1Zqw7oepq2fMedipyhhgFSj5h5ZssyChF",
    thumbnail: "thumbnails/06 Reels and Shorts.png",
  },
  {
    name: "Video 7",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1Fox6vAWiGtuiMDiUnQOTNcJi80X2aoKe",
    thumbnail: "thumbnails/07 Reels and Shorts.png",
  },
  {
    name: "Video 8",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1iVnq0dQh3Y-4bri0AJF5xunkjl0yLw1b",
    thumbnail: "thumbnails/08 Reels and Shorts.png",
  },
  {
    name: "Video 9",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1L1ekDjdLhrNWdjzT3nkQubghq3Qd0MNO",
    thumbnail: "thumbnails/09 Reels and Shorts.png",
  },
  {
    name: "Video 10",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "18IW3QOwWnlpi3qc3yQ7nO22hU2qsP10O",
    thumbnail: "thumbnails/10 Reels and Shorts.png",
  },
  {
    name: "Video 11",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1Wz_H1go3fazHMU2PJDL9Mtj5oHHgFmRj",
    thumbnail: "thumbnails/11 Reels and Shorts.png",
  },
  {
    name: "Video 12",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1ehtnu3xfvUi8zy6goe0rrCvgDrOd1VkP",
    thumbnail: "thumbnails/12 Reels and Shorts.png",
  },
  {
    name: "Video 13",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "14sOGaO5sm4D4j44g3JfjFKGPzyX8FnA9",
    thumbnail: "thumbnails/13 Reels and Shorts.png",
  },
  {
    name: "Video 14",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1SFgMV-n1yDDtXQeg0ERuIiWQXUcEUkGq",
    thumbnail: "thumbnails/14 Reels and Shorts.png",
  },
  {
    name: "Video 15",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "141vMKuzMc5JuAxLpKwcNm7zl7qO2-4vt",
    thumbnail: "thumbnails/15 Reels and Shorts.png",
  },
  {
    name: "Video 16",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "11HcW0Yp-9J36DflXFjiQRS4EZh92odfJ",
    thumbnail: "thumbnails/16 Reels and Shorts.png",
  },
  {
    name: "Video 17",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1eUnngiyOBH96teN14vFgfUwI5rXEjaS7",
    thumbnail: "thumbnails/17 Reels and Shorts.png",
  },
  {
    name: "Video 1",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1o_tAJkN5z94DkaYcuY1LZt2A2Jkdaho0",
    thumbnail: "thumbnails/01 Corporate.png",
  },
  {
    name: "Video 2",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1lxqO05wtLtkvHY-52th-t4Vr_y0XsGl8",
    thumbnail: "thumbnails/02 Corporate.png",
  },
  {
    name: "Video 3",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1ZaJWb69owAXFtW7rDeMz0oHNpDK7P1CN",
    thumbnail: "thumbnails/03 Corporate.png",
  },
  {
    name: "Video 4",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1ZaJWb69owAXFtW7rDeMz0oHNpDK7P1CN",
    thumbnail: "thumbnails/04 Corporate.png",
  },
  {
    name: "Video 4",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1Nv1oxTqHhxPnzeFJ6WK7ucr7PdZofBKV",
    thumbnail: "thumbnails/04 Corporate.png",
  },
  {
    name: "Video 5",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1145WpiO68Q9uy9HkpQ9Via6IhTUC08JR",
    thumbnail: "thumbnails/05 Corporate.png",
  },
  {
    name: "Video 6",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1vj7P5GDD5c09lecFLIt5Tgw-32WyrO58",
    thumbnail: "thumbnails/06 Corporate.png",
  },
  {
    name: "Video 7",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1uyHVnGxZVj9d1q3sVOrjXXl8hQ88YHdI",
    thumbnail: "thumbnails/07 Corporate.png",
  },
  {
    name: "Video 8",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1o0kYY56RQyqCqi6Q-ER3U5FtH9tvRpX8",
    thumbnail: "thumbnails/08 Corporate.png",
  },
  {
    name: "Video 9",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1pOcJ31Xaw_XsZjSh9spsXC9VLS2lINR5",
    thumbnail: "thumbnails/09 Corporate.png",
  },
  {
    name: "Video 10",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "16-g5yW4ISnCthj6l3vAxhDyiV1svPmcY",
    thumbnail: "thumbnails/10 Corporate.png",
  },
  {
    name: "Video 11",
    category: "corporate",
    categoryLabel: "Corporate Videos",
    desc: "Corporate Video",
    driveId: "1QpwF4fVwrKq2qVWo4OnHX1SH_FycWEdz",
    thumbnail: "thumbnails/11 Corporate.png",
  },
  {
    name: "Video 1",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "1DP6ny-uxqXypdEmOrmOp7i709n1Ks94v",
    thumbnail: "thumbnails/01 Cinematic.png",
  },
  {
    name: "Video 2",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "1rSV66T4ou_JmpSLFafjNq-SsozaAx46J",
    thumbnail: "thumbnails/02 Cinematic.png",
  },
  {
    name: "Video 3",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "1sxVPxQ-VANMh1r8JrBrKHQWQj4T6acDY",
    thumbnail: "thumbnails/03 Cinematic.png",
  },
  {
    name: "Video 4",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "16S0cLQvo_Qo0QCr1kZBbvKh6_Ja-vfy",
    thumbnail: "thumbnails/04 Cinematic.png",
  },
  {
    name: "Video 5",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "1XXHebbOgiTIvirqE-PCVnLkiAbI8kHsC",
    thumbnail: "thumbnails/05 Cinematic.png",
  },
  {
    name: "Video 6",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "17yNIf6QA-j8UwjsVz1WfrS1A9eJwSm_5",
    thumbnail: "thumbnails/06 Cinematic.png",
  },
  {
    name: "Video 7",
    category: "cinematic",
    categoryLabel: "Cinematic Videos",
    desc: "Cinematic Video",
    driveId: "15Ia1mscZsQh5lmCVsJTzbLhcregPESOv",
    thumbnail: "thumbnails/07 Cinematic.png",
  },
  {
    name: "Video 1",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1D5M8WwrBaYk3R_s-MTih5Z0AiMoJ3YGH",
    thumbnail: "thumbnails/01 Motion Graphics.png",
  },
  {
    name: "Video 2",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1NS4hgBQ-xEIdIP7U662yD_P4nkjpyvy6",
    thumbnail: "thumbnails/02 Motion Graphics.png",
  },
  {
    name: "Video 3",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1IemO2Z4ItaTAnb2BASzLa0s57fu0sTFB",
    thumbnail: "thumbnails/03 Motion Graphics.png",
  },
  {
    name: "Video 4",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1B6_19l7Zg-H3vADshnIypInAUD0JZ33J",
    thumbnail: "thumbnails/04 Motion Graphics.png",
  },
  {
    name: "Video 5",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1AI5Bz5Xjts6KRyWWZoRRddtaxXts0PXA",
    thumbnail: "thumbnails/05 Motion Graphics.png",
  },
  {
    name: "Video 6",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1SOUSiR11eTMmmxRgBK1RPjkUuSp2InGa",
    thumbnail: "thumbnails/06 Motion Graphics.png",
  },
  {
    name: "Video 7",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "16EzQWIgwEMHRI55RFm1rreFBIIBgpDb0",
    thumbnail: "thumbnails/07 Motion Graphics.png",
  },
  {
    name: "Video 8",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1HX3NQKUlgDEC_dkx1OLdk_T6XUQCJ2qp",
    thumbnail: "thumbnails/08 Motion Graphics.png",
  },
  {
    name: "Video 9",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1psBk4j9Nw-izh2M_ULyCHQZzTVTndiGb",
    thumbnail: "thumbnails/09 Motion Graphics.png",
  },
  {
    name: "Video 10",
    category: "motion-graphics",
    categoryLabel: "motion-graphics Videos",
    desc: "motion-graphics Video",
    driveId: "1yednUyAyx3hnTAXk4Lja9v0ZFm20pE8a",
    thumbnail: "thumbnails/10 Motion Graphics.png",
  },
  {
    name: "Video 1",
    category: "logo-reveal",
    categoryLabel: "logo-reveal Videos",
    desc: "logo-reveal Video",
    driveId: "15QFlt-4G8_Adps7i_dChxvqJSOeBRvXg",
    thumbnail: "thumbnails/Logo Reval 01 copy.png",
  },
  {
    name: "Video  2",
    category: "logo-reveal",
    categoryLabel: "Logo Reveal",
    desc: "Logo Reveal",
    ytId: "VabOmgmCWzU",
  },
  {
    name: "Power Point Presentations 1",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1OdvEwJftl-HOPTYVD49fC1qALCE5KRyF",
  },
  {
    name: "Power Point Presentations 2",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1p_eehpyCWbIWhX3_6rAqrGQPLsYjqBs6",
  },
  {
    name: "Power Point Presentations 3",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1XRWsmwLefRRWu39UicXp9gqv1J90kfcG",
  },
  {
    name: "Power Point Presentations 4",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1uaUnF8_6GSKx8GVuoo9fBmoINJ61H0Cf",
  },
  {
    name: "Power Point Presentations 5",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1OGKmJUROZseuQus0MmqqlvLL2C01b10x",
  },
  {
    name: "Power Point Presentations 6",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "1GU5-my1ylAtNkTENrlTj-1wP8NUogpCL",
  },
  {
    name: "Design 1",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    driveId: "",
  },
];
