const CATEGORY_CONFIG = {
  'reels-shorts': { ratio: '9/16', thumbSize: 'w600-h900' },
  'corporate': { ratio: '16/9', thumbSize: 'w800-h450' },
  'cinematic': { ratio: '21/9', thumbSize: 'w900-h386' },
  'motion-graphics': { ratio: '16/9', thumbSize: 'w800-h450' },
  'logo-reveal': { ratio: '16/9', thumbSize: 'w600-h600' },
  'kineatic-stomp': { ratio: '16/9', thumbSize: 'w800-h450' },
  'ppt-designs': { ratio: '4/3', thumbSize: 'w800-h600' },
  'static-posters': { ratio: '2/3', thumbSize: 'w600-h900' },
  'rotract': { ratio: '16/9', thumbSize: 'w800-h450' },
};

const PORTFOLIO_ITEMS = [
  {
    name: "Video 1",
    category: "kineatic-stomp",
    categoryLabel: "Kineatic and Stomp Typographic Videos",
    desc: "Kineatic and Stomp Typographic Video",
    driveId: "1eREZXf67T2ivna5ot1SFl2YhmXE_fRoh",
    thumbnail: "thumbnails/video1_thumb.png",
  },
  {
    name: "Video 3",
    category: "kineatic-stomp",
    categoryLabel: "Kineatic and Stomp Typographic Videos",
    desc: "Kineatic and Stomp Typographic Video",
    driveId: "1HRoCQJFQ7-PPlTorZdyIx0EmDqf4UgUw",
    thumbnail: "thumbnails/video3_thumb.png",
    revealDelay: 2,
  },
  {
    name: "Video 2",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1wkQernxvuugJ-zT0XVRtTta2ZxdaG-UB",
  },
  {
    name: "Video 3",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1O03Vh6Tz8t4ozANhbrQDwLhN7jxOHNRp",
  },
  {
    name: "Video 4",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1W2IQOgmVsRxXJZ5JeOUOaXLEgRrQTHA9",
  },
  {
    name: "Video 5",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1pWK9OYZ-xdiXZvKePd-rpOElBLvQlAQS",
  },
  {
    name: "Video 6",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1S-QOIpBMS1_25sb2807tcKc4De6bpVQg",
  },
  {
    name: "Video 7",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1r59A1KUKbYPkAVAdnKHj_JcCnLoNq4hX",
  },
  {
    name: "Video 8",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1KcPXWHCJ8IGMyg3esFNtx2ef30i7zN3y",
  },
  {
    name: "Video 9",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1nZKL8V06vdR1fJ_k6_KBKDhNntgDbUn-",
  },
  {
    name: "Video 10",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1ujj1vQUdPXlQx5K2OZ-U7Tet2qSWgr26",
  },
  {
    name: "Video 11",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "107DIrd5zTca_yG2Y-PITvtPfKcmIoMCA",
  },
  {
    name: "Video 12",
    category: "reels-shorts",
    categoryLabel: "Reels and Shorts Videos",
    desc: "Reels and Shorts Video",
    driveId: "1ub7g62VSqFavWJFsfqc_8kCP9pAxLTH8",
  },
  {
    name: "Video 13",
    category: "logo-reveal",
    categoryLabel: "Logo Reveal",
    desc: "Overall Logo Reveal",
    driveId: "15QFlt-4G8_Adps7i_dChxvqJSOeBRvXg",
    thumbnail: "thumbnails/Logo Reval 01.png",
  },
  {
    name: "Video 14",
    category: "logo-reveal",
    categoryLabel: "Logo Reveal",
    desc: "Logo Reveal",
    ytId: "VabOmgmCWzU",
  },
  {
    name: "Video 15",
    category: "ppt-designs",
    categoryLabel: "PPT Designs",
    desc: "PPT Design",
    driveId: "15iDzbQiwikcOIha17zI2QUUG1EtMyk10",
  },
  {
    name: "Design 1",
    category: "static-posters",
    categoryLabel: "Static Posters",
    desc: "Static Poster Design",
    driveId: "1LMxJyZBt3VIzb27wrt8xtCW-dOP-PkiA",
  },
];
